### ISSUE TITLE
Need bootstrap documentation

### ISSUE THREAD

**Issue by deweysasser** [caldwell/http-log-to-statsd#1]
This looks like a very useful package.  Can you document the bootstrap sufficiently for others to use?  It appears to build using RUST but I am completely unfamiliar with rust. I tried a simple "rustc" in the rust docker container and it failed.

Some documentation of process from source to binary would be very helpful.

**Comment by caldwell** [comment]
You're right, I didn't including the compilation stuff because I didn't consider that it's non-obvious to someone who doesn't know Rust. I've added a blurb in the README. `cargo build --release` is the incantation you're looking for.
